package advancementcriteriadisplay;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JTextPane;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author spencersharp
 */
public class AdvancementCriteriaDisplay extends javax.swing.JFrame {

    /**
     * Creates new form MainWindows
     */
    public AdvancementCriteriaDisplay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPane8 = new javax.swing.JTextPane();
        jScrollPane38 = new javax.swing.JScrollPane();
        jTextPane38 = new javax.swing.JTextPane();
        jScrollPane47 = new javax.swing.JScrollPane();
        jTextPane47 = new javax.swing.JTextPane();
        jScrollPane48 = new javax.swing.JScrollPane();
        jTextPane48 = new javax.swing.JTextPane();
        jScrollPane60 = new javax.swing.JScrollPane();
        jTextPane60 = new javax.swing.JTextPane();
        jScrollPane59 = new javax.swing.JScrollPane();
        jTextPane59 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jScrollPane42 = new javax.swing.JScrollPane();
        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane86 = new javax.swing.JScrollPane();
        Inspire1stPlacePane17 = new javax.swing.JTextPane();
        jScrollPane65 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        NumberOfTeamsAdvancingPrimaryPane = new javax.swing.JTextPane();
        jScrollPane66 = new javax.swing.JScrollPane();
        NumberOfTeamsAdvnacingSecondaryPane = new javax.swing.JTextPane();
        jScrollPane67 = new javax.swing.JScrollPane();
        NumberOfTeamsAdvancingPrimaryText = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        Inspire1stPlacePane = new javax.swing.JTextPane();
        jScrollPane68 = new javax.swing.JScrollPane();
        WinningAllianceCaptainPane = new javax.swing.JTextPane();
        jScrollPane70 = new javax.swing.JScrollPane();
        Inspire2ndPlacePane = new javax.swing.JTextPane();
        jScrollPane73 = new javax.swing.JScrollPane();
        NumberOfTeamsAdvancingSecondaryText = new javax.swing.JTextPane();
        jScrollPane41 = new javax.swing.JScrollPane();
        Inspire1stPlaceTeam = new javax.swing.JTextPane();
        jScrollPane71 = new javax.swing.JScrollPane();
        WinningAlliance1stPickPane = new javax.swing.JTextPane();
        jScrollPane72 = new javax.swing.JScrollPane();
        Inspire3rdPlacePane = new javax.swing.JTextPane();
        jScrollPane74 = new javax.swing.JScrollPane();
        WinningAlliance2ndPickPane = new javax.swing.JTextPane();
        jScrollPane75 = new javax.swing.JScrollPane();
        Think1stPlacePane = new javax.swing.JTextPane();
        jScrollPane76 = new javax.swing.JScrollPane();
        FinalistAllianceCaptainPane = new javax.swing.JTextPane();
        jScrollPane77 = new javax.swing.JScrollPane();
        Connect1stPlacePane = new javax.swing.JTextPane();
        jScrollPane78 = new javax.swing.JScrollPane();
        FinalistAlliance1stPickPane = new javax.swing.JTextPane();
        jScrollPane79 = new javax.swing.JScrollPane();
        Innovate1stPlacePane = new javax.swing.JTextPane();
        jScrollPane80 = new javax.swing.JScrollPane();
        FinalistAlliance2ndPickPane = new javax.swing.JTextPane();
        jScrollPane81 = new javax.swing.JScrollPane();
        PTCDesign1stPlacePane = new javax.swing.JTextPane();
        jScrollPane82 = new javax.swing.JScrollPane();
        Motivate1stPlacePane = new javax.swing.JTextPane();
        jScrollPane83 = new javax.swing.JScrollPane();
        Control1stPlacePane = new javax.swing.JTextPane();
        jScrollPane43 = new javax.swing.JScrollPane();
        WinningAllianceCaptainTeam = new javax.swing.JTextPane();
        jScrollPane44 = new javax.swing.JScrollPane();
        Inspire2ndPlaceTeam = new javax.swing.JTextPane();
        jScrollPane45 = new javax.swing.JScrollPane();
        WinningAlliance1stPickTeam = new javax.swing.JTextPane();
        jScrollPane46 = new javax.swing.JScrollPane();
        Inspire3rdPlaceTeam = new javax.swing.JTextPane();
        jScrollPane49 = new javax.swing.JScrollPane();
        WinningAlliance2ndPickTeam = new javax.swing.JTextPane();
        jScrollPane50 = new javax.swing.JScrollPane();
        Think1stPlaceTeam = new javax.swing.JTextPane();
        jScrollPane51 = new javax.swing.JScrollPane();
        FinalistAllianceCaptainTeam = new javax.swing.JTextPane();
        jScrollPane52 = new javax.swing.JScrollPane();
        Connect1stPlaceTeam = new javax.swing.JTextPane();
        jScrollPane53 = new javax.swing.JScrollPane();
        FinalistAlliance1stPickTeam = new javax.swing.JTextPane();
        jScrollPane54 = new javax.swing.JScrollPane();
        Innovate1stPlaceTeam = new javax.swing.JTextPane();
        jScrollPane55 = new javax.swing.JScrollPane();
        FinalistAlliance2ndPickTeam = new javax.swing.JTextPane();
        jScrollPane56 = new javax.swing.JScrollPane();
        PTCDesign1stPlaceTeam = new javax.swing.JTextPane();
        jScrollPane57 = new javax.swing.JScrollPane();
        Motivate1stPlaceTeam = new javax.swing.JTextPane();
        jScrollPane58 = new javax.swing.JScrollPane();
        HighestRankedWinningDivTeam1 = new javax.swing.JTextPane();
        jScrollPane61 = new javax.swing.JScrollPane();
        Control1stPlaceTeam = new javax.swing.JTextPane();
        jScrollPane84 = new javax.swing.JScrollPane();
        HighestRankedWinningDivPane1 = new javax.swing.JTextPane();
        jScrollPane85 = new javax.swing.JScrollPane();
        Think2ndPlacePane = new javax.swing.JTextPane();
        jScrollPane87 = new javax.swing.JScrollPane();
        HighestRankedFinalistDivPane1 = new javax.swing.JTextPane();
        jScrollPane88 = new javax.swing.JScrollPane();
        Connect2ndPlacePane = new javax.swing.JTextPane();
        jScrollPane89 = new javax.swing.JScrollPane();
        HighestRankedWinningDivPane2 = new javax.swing.JTextPane();
        jScrollPane62 = new javax.swing.JScrollPane();
        Think2ndPlaceTeam = new javax.swing.JTextPane();
        jScrollPane63 = new javax.swing.JScrollPane();
        HighestRankedFinalistDivTeam1 = new javax.swing.JTextPane();
        jScrollPane64 = new javax.swing.JScrollPane();
        Connect2ndPlaceTeam = new javax.swing.JTextPane();
        jScrollPane69 = new javax.swing.JScrollPane();
        HighestRankedWinningDivTeam2 = new javax.swing.JTextPane();
        jScrollPane90 = new javax.swing.JScrollPane();
        Innovate2ndPlacePane = new javax.swing.JTextPane();
        jScrollPane91 = new javax.swing.JScrollPane();
        Inspire1stPlacePane22 = new javax.swing.JTextPane();
        jScrollPane92 = new javax.swing.JScrollPane();
        Inspire1stPlacePane23 = new javax.swing.JTextPane();
        jScrollPane93 = new javax.swing.JScrollPane();
        Inspire1stPlacePane24 = new javax.swing.JTextPane();
        jScrollPane94 = new javax.swing.JScrollPane();
        Inspire1stPlacePane25 = new javax.swing.JTextPane();
        jScrollPane95 = new javax.swing.JScrollPane();
        Inspire1stPlacePane26 = new javax.swing.JTextPane();
        jScrollPane97 = new javax.swing.JScrollPane();
        Innovate2ndPlaceTeam = new javax.swing.JTextPane();
        jScrollPane98 = new javax.swing.JScrollPane();
        WinningAllianceCaptainTeam22 = new javax.swing.JTextPane();
        jScrollPane99 = new javax.swing.JScrollPane();
        WinningAllianceCaptainTeam23 = new javax.swing.JTextPane();
        jScrollPane100 = new javax.swing.JScrollPane();
        WinningAllianceCaptainTeam24 = new javax.swing.JTextPane();
        jScrollPane101 = new javax.swing.JScrollPane();
        WinningAllianceCaptainTeam25 = new javax.swing.JTextPane();
        jScrollPane103 = new javax.swing.JScrollPane();
        WinningAllianceCaptainTeam27 = new javax.swing.JTextPane();
        jScrollPane96 = new javax.swing.JScrollPane();
        Inspire1stPlacePane27 = new javax.swing.JTextPane();
        jScrollPane102 = new javax.swing.JScrollPane();
        Inspire1stPlacePane28 = new javax.swing.JTextPane();
        jScrollPane104 = new javax.swing.JScrollPane();
        Inspire1stPlacePane29 = new javax.swing.JTextPane();
        jScrollPane105 = new javax.swing.JScrollPane();
        Inspire1stPlacePane30 = new javax.swing.JTextPane();
        jScrollPane106 = new javax.swing.JScrollPane();
        Inspire1stPlacePane31 = new javax.swing.JTextPane();
        jScrollPane107 = new javax.swing.JScrollPane();
        Inspire1stPlacePane32 = new javax.swing.JTextPane();
        jScrollPane108 = new javax.swing.JScrollPane();
        Inspire1stPlacePane33 = new javax.swing.JTextPane();
        jScrollPane109 = new javax.swing.JScrollPane();
        Inspire1stPlacePane34 = new javax.swing.JTextPane();
        jScrollPane110 = new javax.swing.JScrollPane();
        Inspire1stPlacePane35 = new javax.swing.JTextPane();
        jScrollPane111 = new javax.swing.JScrollPane();
        Inspire1stPlacePane36 = new javax.swing.JTextPane();
        jScrollPane112 = new javax.swing.JScrollPane();
        Inspire1stPlacePane37 = new javax.swing.JTextPane();
        jScrollPane113 = new javax.swing.JScrollPane();
        Inspire1stPlacePane38 = new javax.swing.JTextPane();
        jScrollPane114 = new javax.swing.JScrollPane();
        Inspire1stPlacePane39 = new javax.swing.JTextPane();
        jScrollPane115 = new javax.swing.JScrollPane();
        Inspire1stPlacePane40 = new javax.swing.JTextPane();
        jScrollPane116 = new javax.swing.JScrollPane();
        WinningAllianceCaptainTeam28 = new javax.swing.JTextPane();
        jScrollPane117 = new javax.swing.JScrollPane();
        WinningAllianceCaptainTeam29 = new javax.swing.JTextPane();
        jScrollPane118 = new javax.swing.JScrollPane();
        WinningAllianceCaptainTeam30 = new javax.swing.JTextPane();
        jScrollPane119 = new javax.swing.JScrollPane();
        WinningAllianceCaptainTeam31 = new javax.swing.JTextPane();
        jScrollPane120 = new javax.swing.JScrollPane();
        WinningAllianceCaptainTeam32 = new javax.swing.JTextPane();
        jScrollPane121 = new javax.swing.JScrollPane();
        WinningAllianceCaptainTeam33 = new javax.swing.JTextPane();
        jScrollPane122 = new javax.swing.JScrollPane();
        WinningAllianceCaptainTeam34 = new javax.swing.JTextPane();
        jScrollPane123 = new javax.swing.JScrollPane();
        WinningAllianceCaptainTeam35 = new javax.swing.JTextPane();
        jScrollPane124 = new javax.swing.JScrollPane();
        WinningAllianceCaptainTeam36 = new javax.swing.JTextPane();
        jScrollPane125 = new javax.swing.JScrollPane();
        WinningAllianceCaptainTeam37 = new javax.swing.JTextPane();
        jScrollPane126 = new javax.swing.JScrollPane();
        WinningAllianceCaptainTeam38 = new javax.swing.JTextPane();
        jScrollPane127 = new javax.swing.JScrollPane();
        WinningAllianceCaptainTeam39 = new javax.swing.JTextPane();
        jScrollPane128 = new javax.swing.JScrollPane();
        WinningAllianceCaptainTeam40 = new javax.swing.JTextPane();
        jScrollPane129 = new javax.swing.JScrollPane();
        WinningAllianceCaptainTeam41 = new javax.swing.JTextPane();

        jTextPane8.setEditable(false);
        jTextPane8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jTextPane8.setText("Inspire 1st Place");
        jScrollPane8.setViewportView(jTextPane8);

        jTextPane38.setEditable(false);
        jTextPane38.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jTextPane38.setText("Inspire 1st Place");
        jScrollPane38.setViewportView(jTextPane38);

        jTextPane47.setEditable(false);
        jTextPane47.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jTextPane47.setText("Highest Ranked Team");
        jScrollPane47.setViewportView(jTextPane47);

        jTextPane48.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jTextPane48.setText("11503");
        jScrollPane48.setViewportView(jTextPane48);

        jTextPane60.setEditable(false);
        jTextPane60.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jTextPane60.setText("Highest Ranked Team");
        jScrollPane60.setViewportView(jTextPane60);

        jTextPane59.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jTextPane59.setText("11503");
        jScrollPane59.setViewportView(jTextPane59);

        jMenuItem1.setText("jMenuItem1");

        Inspire1stPlacePane17.setEditable(false);
        Inspire1stPlacePane17.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Inspire1stPlacePane17.setText("Inspire 1st Place");
        jScrollPane86.setViewportView(Inspire1stPlacePane17);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane65.setMaximumSize(new java.awt.Dimension(468, 1500));
        jScrollPane65.setMinimumSize(new java.awt.Dimension(468, 1500));
        jScrollPane65.setPreferredSize(new java.awt.Dimension(468, 800));

        jPanel1.setMaximumSize(new java.awt.Dimension(450, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(450, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 800));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Advancements");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 6, 484, 43);

        NumberOfTeamsAdvancingPrimaryPane.setEditable(false);
        NumberOfTeamsAdvancingPrimaryPane.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        NumberOfTeamsAdvancingPrimaryPane.setText("# of Teams Advancing (Primary):");
        NumberOfTeamsAdvancingPrimaryPane.setAutoscrolls(false);
        NumberOfTeamsAdvancingPrimaryPane.setDragEnabled(false);
        jScrollPane5.setViewportView(NumberOfTeamsAdvancingPrimaryPane);

        jPanel1.add(jScrollPane5);
        jScrollPane5.setBounds(0, 55, 344, 36);

        NumberOfTeamsAdvnacingSecondaryPane.setEditable(false);
        NumberOfTeamsAdvnacingSecondaryPane.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        NumberOfTeamsAdvnacingSecondaryPane.setText("# of Teams Advancing (Secondary):");
        NumberOfTeamsAdvnacingSecondaryPane.setAutoscrolls(false);
        NumberOfTeamsAdvnacingSecondaryPane.setDragEnabled(false);
        jScrollPane66.setViewportView(NumberOfTeamsAdvnacingSecondaryPane);

        jPanel1.add(jScrollPane66);
        jScrollPane66.setBounds(0, 97, 344, 36);

        NumberOfTeamsAdvancingPrimaryText.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        NumberOfTeamsAdvancingPrimaryText.setText("11503");
        jScrollPane67.setViewportView(NumberOfTeamsAdvancingPrimaryText);

        jPanel1.add(jScrollPane67);
        jScrollPane67.setBounds(350, 55, 96, 36);

        Inspire1stPlacePane.setEditable(false);
        Inspire1stPlacePane.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Inspire1stPlacePane.setText("Inspire 1st Place");
        jScrollPane1.setViewportView(Inspire1stPlacePane);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 151, 344, 26);

        WinningAllianceCaptainPane.setEditable(false);
        WinningAllianceCaptainPane.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        WinningAllianceCaptainPane.setText("Winning Alliance Captain");
        jScrollPane68.setViewportView(WinningAllianceCaptainPane);

        jPanel1.add(jScrollPane68);
        jScrollPane68.setBounds(0, 183, 344, 26);

        Inspire2ndPlacePane.setEditable(false);
        Inspire2ndPlacePane.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Inspire2ndPlacePane.setText("Inspire 2nd Place");
        jScrollPane70.setViewportView(Inspire2ndPlacePane);

        jPanel1.add(jScrollPane70);
        jScrollPane70.setBounds(0, 215, 344, 26);

        NumberOfTeamsAdvancingSecondaryText.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        NumberOfTeamsAdvancingSecondaryText.setText("11503");
        jScrollPane73.setViewportView(NumberOfTeamsAdvancingSecondaryText);

        jPanel1.add(jScrollPane73);
        jScrollPane73.setBounds(350, 97, 96, 36);

        Inspire1stPlaceTeam.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Inspire1stPlaceTeam.setText("11503");
        jScrollPane41.setViewportView(Inspire1stPlaceTeam);

        jPanel1.add(jScrollPane41);
        jScrollPane41.setBounds(350, 151, 96, 26);

        WinningAlliance1stPickPane.setEditable(false);
        WinningAlliance1stPickPane.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        WinningAlliance1stPickPane.setText("Winning Alliance 1st Pick");
        jScrollPane71.setViewportView(WinningAlliance1stPickPane);

        jPanel1.add(jScrollPane71);
        jScrollPane71.setBounds(0, 247, 344, 26);

        Inspire3rdPlacePane.setEditable(false);
        Inspire3rdPlacePane.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Inspire3rdPlacePane.setText("Inspire 3rd Place");
        jScrollPane72.setViewportView(Inspire3rdPlacePane);

        jPanel1.add(jScrollPane72);
        jScrollPane72.setBounds(0, 279, 344, 26);

        WinningAlliance2ndPickPane.setEditable(false);
        WinningAlliance2ndPickPane.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        WinningAlliance2ndPickPane.setText("Winning Alliance 2nd Pick");
        jScrollPane74.setViewportView(WinningAlliance2ndPickPane);

        jPanel1.add(jScrollPane74);
        jScrollPane74.setBounds(0, 311, 344, 26);

        Think1stPlacePane.setEditable(false);
        Think1stPlacePane.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Think1stPlacePane.setText("Think 1st Place");
        jScrollPane75.setViewportView(Think1stPlacePane);

        jPanel1.add(jScrollPane75);
        jScrollPane75.setBounds(0, 343, 344, 26);

        FinalistAllianceCaptainPane.setEditable(false);
        FinalistAllianceCaptainPane.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        FinalistAllianceCaptainPane.setText("Finalist Alliance Captain");
        jScrollPane76.setViewportView(FinalistAllianceCaptainPane);

        jPanel1.add(jScrollPane76);
        jScrollPane76.setBounds(0, 375, 344, 26);

        Connect1stPlacePane.setEditable(false);
        Connect1stPlacePane.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Connect1stPlacePane.setText("Connect 1st Place");
        jScrollPane77.setViewportView(Connect1stPlacePane);

        jPanel1.add(jScrollPane77);
        jScrollPane77.setBounds(0, 407, 344, 26);

        FinalistAlliance1stPickPane.setEditable(false);
        FinalistAlliance1stPickPane.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        FinalistAlliance1stPickPane.setText("Finalist Alliance 1st Pick");
        jScrollPane78.setViewportView(FinalistAlliance1stPickPane);

        jPanel1.add(jScrollPane78);
        jScrollPane78.setBounds(0, 439, 344, 26);

        Innovate1stPlacePane.setEditable(false);
        Innovate1stPlacePane.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Innovate1stPlacePane.setText("Innovate 1st Place");
        jScrollPane79.setViewportView(Innovate1stPlacePane);

        jPanel1.add(jScrollPane79);
        jScrollPane79.setBounds(0, 471, 344, 26);

        FinalistAlliance2ndPickPane.setEditable(false);
        FinalistAlliance2ndPickPane.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        FinalistAlliance2ndPickPane.setText("Finalist Alliance 2nd Pick");
        jScrollPane80.setViewportView(FinalistAlliance2ndPickPane);

        jPanel1.add(jScrollPane80);
        jScrollPane80.setBounds(0, 503, 344, 26);

        PTCDesign1stPlacePane.setEditable(false);
        PTCDesign1stPlacePane.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        PTCDesign1stPlacePane.setText("PTC Design 1st Place");
        jScrollPane81.setViewportView(PTCDesign1stPlacePane);

        jPanel1.add(jScrollPane81);
        jScrollPane81.setBounds(0, 535, 344, 26);

        Motivate1stPlacePane.setEditable(false);
        Motivate1stPlacePane.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Motivate1stPlacePane.setText("Motivate 1st Place");
        jScrollPane82.setViewportView(Motivate1stPlacePane);

        jPanel1.add(jScrollPane82);
        jScrollPane82.setBounds(0, 567, 344, 26);

        Control1stPlacePane.setEditable(false);
        Control1stPlacePane.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Control1stPlacePane.setText("Control 1st Place");
        jScrollPane83.setViewportView(Control1stPlacePane);

        jPanel1.add(jScrollPane83);
        jScrollPane83.setBounds(0, 599, 344, 26);

        WinningAllianceCaptainTeam.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        WinningAllianceCaptainTeam.setText("11503");
        jScrollPane43.setViewportView(WinningAllianceCaptainTeam);

        jPanel1.add(jScrollPane43);
        jScrollPane43.setBounds(350, 183, 96, 26);

        Inspire2ndPlaceTeam.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Inspire2ndPlaceTeam.setText("11503");
        jScrollPane44.setViewportView(Inspire2ndPlaceTeam);

        jPanel1.add(jScrollPane44);
        jScrollPane44.setBounds(350, 215, 96, 26);

        WinningAlliance1stPickTeam.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        WinningAlliance1stPickTeam.setText("11503");
        jScrollPane45.setViewportView(WinningAlliance1stPickTeam);

        jPanel1.add(jScrollPane45);
        jScrollPane45.setBounds(350, 247, 96, 26);

        Inspire3rdPlaceTeam.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Inspire3rdPlaceTeam.setText("11503");
        jScrollPane46.setViewportView(Inspire3rdPlaceTeam);

        jPanel1.add(jScrollPane46);
        jScrollPane46.setBounds(350, 279, 96, 26);

        WinningAlliance2ndPickTeam.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        WinningAlliance2ndPickTeam.setText("11503");
        jScrollPane49.setViewportView(WinningAlliance2ndPickTeam);

        jPanel1.add(jScrollPane49);
        jScrollPane49.setBounds(350, 311, 96, 26);

        Think1stPlaceTeam.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Think1stPlaceTeam.setText("11503");
        jScrollPane50.setViewportView(Think1stPlaceTeam);

        jPanel1.add(jScrollPane50);
        jScrollPane50.setBounds(350, 343, 96, 26);

        FinalistAllianceCaptainTeam.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        FinalistAllianceCaptainTeam.setText("11503");
        jScrollPane51.setViewportView(FinalistAllianceCaptainTeam);

        jPanel1.add(jScrollPane51);
        jScrollPane51.setBounds(350, 375, 96, 26);

        Connect1stPlaceTeam.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Connect1stPlaceTeam.setText("11503");
        jScrollPane52.setViewportView(Connect1stPlaceTeam);

        jPanel1.add(jScrollPane52);
        jScrollPane52.setBounds(350, 407, 96, 26);

        FinalistAlliance1stPickTeam.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        FinalistAlliance1stPickTeam.setText("11503");
        jScrollPane53.setViewportView(FinalistAlliance1stPickTeam);

        jPanel1.add(jScrollPane53);
        jScrollPane53.setBounds(350, 439, 96, 26);

        Innovate1stPlaceTeam.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Innovate1stPlaceTeam.setText("11503");
        jScrollPane54.setViewportView(Innovate1stPlaceTeam);

        jPanel1.add(jScrollPane54);
        jScrollPane54.setBounds(350, 471, 96, 26);

        FinalistAlliance2ndPickTeam.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        FinalistAlliance2ndPickTeam.setText("11503");
        jScrollPane55.setViewportView(FinalistAlliance2ndPickTeam);

        jPanel1.add(jScrollPane55);
        jScrollPane55.setBounds(350, 503, 96, 26);

        PTCDesign1stPlaceTeam.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        PTCDesign1stPlaceTeam.setText("11503");
        jScrollPane56.setViewportView(PTCDesign1stPlaceTeam);

        jPanel1.add(jScrollPane56);
        jScrollPane56.setBounds(350, 535, 96, 26);

        Motivate1stPlaceTeam.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Motivate1stPlaceTeam.setText("11503");
        jScrollPane57.setViewportView(Motivate1stPlaceTeam);

        jPanel1.add(jScrollPane57);
        jScrollPane57.setBounds(350, 567, 96, 26);

        HighestRankedWinningDivTeam1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        HighestRankedWinningDivTeam1.setText("11503");
        jScrollPane58.setViewportView(HighestRankedWinningDivTeam1);

        jPanel1.add(jScrollPane58);
        jScrollPane58.setBounds(350, 631, 96, 26);

        Control1stPlaceTeam.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Control1stPlaceTeam.setText("11503");
        jScrollPane61.setViewportView(Control1stPlaceTeam);

        jPanel1.add(jScrollPane61);
        jScrollPane61.setBounds(350, 599, 96, 26);

        HighestRankedWinningDivPane1.setEditable(false);
        HighestRankedWinningDivPane1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        HighestRankedWinningDivPane1.setText("Highest Ranked Winning Div.");
        jScrollPane84.setViewportView(HighestRankedWinningDivPane1);

        jPanel1.add(jScrollPane84);
        jScrollPane84.setBounds(0, 631, 344, 26);

        Think2ndPlacePane.setEditable(false);
        Think2ndPlacePane.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Think2ndPlacePane.setText("Think 2nd Place");
        jScrollPane85.setViewportView(Think2ndPlacePane);

        jPanel1.add(jScrollPane85);
        jScrollPane85.setBounds(0, 663, 344, 26);

        HighestRankedFinalistDivPane1.setEditable(false);
        HighestRankedFinalistDivPane1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        HighestRankedFinalistDivPane1.setText("Highest Ranked Finalist Div.");
        jScrollPane87.setViewportView(HighestRankedFinalistDivPane1);

        jPanel1.add(jScrollPane87);
        jScrollPane87.setBounds(0, 695, 344, 26);

        Connect2ndPlacePane.setEditable(false);
        Connect2ndPlacePane.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Connect2ndPlacePane.setText("Connect 2nd Place");
        jScrollPane88.setViewportView(Connect2ndPlacePane);

        jPanel1.add(jScrollPane88);
        jScrollPane88.setBounds(0, 727, 344, 26);

        HighestRankedWinningDivPane2.setEditable(false);
        HighestRankedWinningDivPane2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        HighestRankedWinningDivPane2.setText("Highest Ranked Winning Div.");
        jScrollPane89.setViewportView(HighestRankedWinningDivPane2);

        jPanel1.add(jScrollPane89);
        jScrollPane89.setBounds(0, 759, 344, 26);

        Think2ndPlaceTeam.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Think2ndPlaceTeam.setText("11503");
        jScrollPane62.setViewportView(Think2ndPlaceTeam);

        jPanel1.add(jScrollPane62);
        jScrollPane62.setBounds(350, 663, 96, 26);

        HighestRankedFinalistDivTeam1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        HighestRankedFinalistDivTeam1.setText("11503");
        jScrollPane63.setViewportView(HighestRankedFinalistDivTeam1);

        jPanel1.add(jScrollPane63);
        jScrollPane63.setBounds(350, 695, 96, 26);

        Connect2ndPlaceTeam.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Connect2ndPlaceTeam.setText("11503");
        jScrollPane64.setViewportView(Connect2ndPlaceTeam);

        jPanel1.add(jScrollPane64);
        jScrollPane64.setBounds(350, 727, 96, 26);

        HighestRankedWinningDivTeam2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        HighestRankedWinningDivTeam2.setText("11503");
        jScrollPane69.setViewportView(HighestRankedWinningDivTeam2);

        jPanel1.add(jScrollPane69);
        jScrollPane69.setBounds(350, 759, 96, 26);

        Innovate2ndPlacePane.setEditable(false);
        Innovate2ndPlacePane.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Innovate2ndPlacePane.setText("Innovate 2nd Place");
        jScrollPane90.setViewportView(Innovate2ndPlacePane);

        jPanel1.add(jScrollPane90);
        jScrollPane90.setBounds(0, 791, 344, 26);

        Inspire1stPlacePane22.setEditable(false);
        Inspire1stPlacePane22.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Inspire1stPlacePane22.setText("Highest Ranked Finalist Div.");
        jScrollPane91.setViewportView(Inspire1stPlacePane22);

        jPanel1.add(jScrollPane91);
        jScrollPane91.setBounds(0, 823, 344, 26);

        Inspire1stPlacePane23.setEditable(false);
        Inspire1stPlacePane23.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Inspire1stPlacePane23.setText("PTC Design 2nd Place");
        jScrollPane92.setViewportView(Inspire1stPlacePane23);

        jPanel1.add(jScrollPane92);
        jScrollPane92.setBounds(0, 855, 344, 26);

        Inspire1stPlacePane24.setEditable(false);
        Inspire1stPlacePane24.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Inspire1stPlacePane24.setText("Highest Ranked Winning Div.");
        jScrollPane93.setViewportView(Inspire1stPlacePane24);

        jPanel1.add(jScrollPane93);
        jScrollPane93.setBounds(0, 887, 344, 26);

        Inspire1stPlacePane25.setEditable(false);
        Inspire1stPlacePane25.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Inspire1stPlacePane25.setText("Motivate 2nd Place");
        jScrollPane94.setViewportView(Inspire1stPlacePane25);

        jPanel1.add(jScrollPane94);
        jScrollPane94.setBounds(0, 919, 344, 26);

        Inspire1stPlacePane26.setEditable(false);
        Inspire1stPlacePane26.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Inspire1stPlacePane26.setText("Highest Ranked Finalist Div.");
        jScrollPane95.setViewportView(Inspire1stPlacePane26);

        jPanel1.add(jScrollPane95);
        jScrollPane95.setBounds(0, 951, 344, 26);

        Innovate2ndPlaceTeam.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Innovate2ndPlaceTeam.setText("11503");
        jScrollPane97.setViewportView(Innovate2ndPlaceTeam);

        jPanel1.add(jScrollPane97);
        jScrollPane97.setBounds(350, 791, 96, 26);

        WinningAllianceCaptainTeam22.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        WinningAllianceCaptainTeam22.setText("11503");
        jScrollPane98.setViewportView(WinningAllianceCaptainTeam22);

        jPanel1.add(jScrollPane98);
        jScrollPane98.setBounds(350, 823, 96, 26);

        WinningAllianceCaptainTeam23.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        WinningAllianceCaptainTeam23.setText("11503");
        jScrollPane99.setViewportView(WinningAllianceCaptainTeam23);

        jPanel1.add(jScrollPane99);
        jScrollPane99.setBounds(350, 855, 96, 26);

        WinningAllianceCaptainTeam24.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        WinningAllianceCaptainTeam24.setText("11503");
        jScrollPane100.setViewportView(WinningAllianceCaptainTeam24);

        jPanel1.add(jScrollPane100);
        jScrollPane100.setBounds(350, 887, 96, 26);

        WinningAllianceCaptainTeam25.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        WinningAllianceCaptainTeam25.setText("11503");
        jScrollPane101.setViewportView(WinningAllianceCaptainTeam25);

        jPanel1.add(jScrollPane101);
        jScrollPane101.setBounds(350, 919, 96, 26);

        WinningAllianceCaptainTeam27.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        WinningAllianceCaptainTeam27.setText("11503");
        jScrollPane103.setViewportView(WinningAllianceCaptainTeam27);

        jPanel1.add(jScrollPane103);
        jScrollPane103.setBounds(350, 951, 96, 26);

        Inspire1stPlacePane27.setEditable(false);
        Inspire1stPlacePane27.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Inspire1stPlacePane27.setText("Control 2nd Place");
        jScrollPane96.setViewportView(Inspire1stPlacePane27);

        jPanel1.add(jScrollPane96);
        jScrollPane96.setBounds(0, 983, 344, 26);

        Inspire1stPlacePane28.setEditable(false);
        Inspire1stPlacePane28.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Inspire1stPlacePane28.setText("Highest Ranked Winning Div.");
        jScrollPane102.setViewportView(Inspire1stPlacePane28);

        jPanel1.add(jScrollPane102);
        jScrollPane102.setBounds(0, 1015, 344, 26);

        Inspire1stPlacePane29.setEditable(false);
        Inspire1stPlacePane29.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Inspire1stPlacePane29.setText("Think 3rd Place");
        jScrollPane104.setViewportView(Inspire1stPlacePane29);

        jPanel1.add(jScrollPane104);
        jScrollPane104.setBounds(0, 1047, 344, 26);

        Inspire1stPlacePane30.setEditable(false);
        Inspire1stPlacePane30.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Inspire1stPlacePane30.setText("Highest Ranked Finalist Div.");
        jScrollPane105.setViewportView(Inspire1stPlacePane30);

        jPanel1.add(jScrollPane105);
        jScrollPane105.setBounds(0, 1079, 344, 26);

        Inspire1stPlacePane31.setEditable(false);
        Inspire1stPlacePane31.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Inspire1stPlacePane31.setText("Connect 3rd Place");
        jScrollPane106.setViewportView(Inspire1stPlacePane31);

        jPanel1.add(jScrollPane106);
        jScrollPane106.setBounds(0, 1111, 344, 26);

        Inspire1stPlacePane32.setEditable(false);
        Inspire1stPlacePane32.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Inspire1stPlacePane32.setText("Highest Ranked Winning Div.");
        jScrollPane107.setViewportView(Inspire1stPlacePane32);

        jPanel1.add(jScrollPane107);
        jScrollPane107.setBounds(0, 1143, 344, 26);

        Inspire1stPlacePane33.setEditable(false);
        Inspire1stPlacePane33.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Inspire1stPlacePane33.setText("Innovate 3rd Place");
        jScrollPane108.setViewportView(Inspire1stPlacePane33);

        jPanel1.add(jScrollPane108);
        jScrollPane108.setBounds(0, 1175, 344, 26);

        Inspire1stPlacePane34.setEditable(false);
        Inspire1stPlacePane34.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Inspire1stPlacePane34.setText("Highest Ranked Finalist Div.");
        jScrollPane109.setViewportView(Inspire1stPlacePane34);

        jPanel1.add(jScrollPane109);
        jScrollPane109.setBounds(0, 1207, 344, 26);

        Inspire1stPlacePane35.setEditable(false);
        Inspire1stPlacePane35.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Inspire1stPlacePane35.setText("PTC Design 3rd Place");
        jScrollPane110.setViewportView(Inspire1stPlacePane35);

        jPanel1.add(jScrollPane110);
        jScrollPane110.setBounds(0, 1239, 344, 26);

        Inspire1stPlacePane36.setEditable(false);
        Inspire1stPlacePane36.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Inspire1stPlacePane36.setText("Highest Ranked Winning Div.");
        jScrollPane111.setViewportView(Inspire1stPlacePane36);

        jPanel1.add(jScrollPane111);
        jScrollPane111.setBounds(0, 1271, 344, 26);

        Inspire1stPlacePane37.setEditable(false);
        Inspire1stPlacePane37.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Inspire1stPlacePane37.setText("Motivate 3rd Place");
        jScrollPane112.setViewportView(Inspire1stPlacePane37);

        jPanel1.add(jScrollPane112);
        jScrollPane112.setBounds(0, 1303, 344, 26);

        Inspire1stPlacePane38.setEditable(false);
        Inspire1stPlacePane38.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Inspire1stPlacePane38.setText("Highest Ranked Finalist Div.");
        jScrollPane113.setViewportView(Inspire1stPlacePane38);

        jPanel1.add(jScrollPane113);
        jScrollPane113.setBounds(0, 1335, 344, 26);

        Inspire1stPlacePane39.setEditable(false);
        Inspire1stPlacePane39.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Inspire1stPlacePane39.setText("Control 3rd Place");
        jScrollPane114.setViewportView(Inspire1stPlacePane39);

        jPanel1.add(jScrollPane114);
        jScrollPane114.setBounds(0, 1367, 344, 26);

        Inspire1stPlacePane40.setEditable(false);
        Inspire1stPlacePane40.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Inspire1stPlacePane40.setText("Highest Ranked Winning Div.");
        jScrollPane115.setViewportView(Inspire1stPlacePane40);

        jPanel1.add(jScrollPane115);
        jScrollPane115.setBounds(0, 1399, 344, 26);

        WinningAllianceCaptainTeam28.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        WinningAllianceCaptainTeam28.setText("11503");
        jScrollPane116.setViewportView(WinningAllianceCaptainTeam28);

        jPanel1.add(jScrollPane116);
        jScrollPane116.setBounds(350, 983, 96, 26);

        WinningAllianceCaptainTeam29.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        WinningAllianceCaptainTeam29.setText("11503");
        jScrollPane117.setViewportView(WinningAllianceCaptainTeam29);

        jPanel1.add(jScrollPane117);
        jScrollPane117.setBounds(350, 1015, 96, 26);

        WinningAllianceCaptainTeam30.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        WinningAllianceCaptainTeam30.setText("11503");
        jScrollPane118.setViewportView(WinningAllianceCaptainTeam30);

        jPanel1.add(jScrollPane118);
        jScrollPane118.setBounds(350, 1047, 96, 26);

        WinningAllianceCaptainTeam31.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        WinningAllianceCaptainTeam31.setText("11503");
        jScrollPane119.setViewportView(WinningAllianceCaptainTeam31);

        jPanel1.add(jScrollPane119);
        jScrollPane119.setBounds(350, 1079, 96, 26);

        WinningAllianceCaptainTeam32.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        WinningAllianceCaptainTeam32.setText("11503");
        jScrollPane120.setViewportView(WinningAllianceCaptainTeam32);

        jPanel1.add(jScrollPane120);
        jScrollPane120.setBounds(350, 1111, 96, 26);

        WinningAllianceCaptainTeam33.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        WinningAllianceCaptainTeam33.setText("11503");
        jScrollPane121.setViewportView(WinningAllianceCaptainTeam33);

        jPanel1.add(jScrollPane121);
        jScrollPane121.setBounds(350, 1143, 96, 26);

        WinningAllianceCaptainTeam34.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        WinningAllianceCaptainTeam34.setText("11503");
        jScrollPane122.setViewportView(WinningAllianceCaptainTeam34);

        jPanel1.add(jScrollPane122);
        jScrollPane122.setBounds(350, 1175, 96, 26);

        WinningAllianceCaptainTeam35.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        WinningAllianceCaptainTeam35.setText("11503");
        jScrollPane123.setViewportView(WinningAllianceCaptainTeam35);

        jPanel1.add(jScrollPane123);
        jScrollPane123.setBounds(350, 1207, 96, 26);

        WinningAllianceCaptainTeam36.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        WinningAllianceCaptainTeam36.setText("11503");
        jScrollPane124.setViewportView(WinningAllianceCaptainTeam36);

        jPanel1.add(jScrollPane124);
        jScrollPane124.setBounds(350, 1239, 96, 26);

        WinningAllianceCaptainTeam37.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        WinningAllianceCaptainTeam37.setText("11503");
        jScrollPane125.setViewportView(WinningAllianceCaptainTeam37);

        jPanel1.add(jScrollPane125);
        jScrollPane125.setBounds(350, 1271, 96, 26);

        WinningAllianceCaptainTeam38.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        WinningAllianceCaptainTeam38.setText("11503");
        jScrollPane126.setViewportView(WinningAllianceCaptainTeam38);

        jPanel1.add(jScrollPane126);
        jScrollPane126.setBounds(350, 1303, 96, 26);

        WinningAllianceCaptainTeam39.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        WinningAllianceCaptainTeam39.setText("11503");
        jScrollPane127.setViewportView(WinningAllianceCaptainTeam39);

        jPanel1.add(jScrollPane127);
        jScrollPane127.setBounds(350, 1335, 96, 26);

        WinningAllianceCaptainTeam40.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        WinningAllianceCaptainTeam40.setText("11503");
        jScrollPane128.setViewportView(WinningAllianceCaptainTeam40);

        jPanel1.add(jScrollPane128);
        jScrollPane128.setBounds(350, 1367, 96, 26);

        WinningAllianceCaptainTeam41.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        WinningAllianceCaptainTeam41.setText("11503");
        jScrollPane129.setViewportView(WinningAllianceCaptainTeam41);

        jPanel1.add(jScrollPane129);
        jScrollPane129.setBounds(350, 1399, 96, 26);

        jScrollPane65.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane65, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane65, javax.swing.GroupLayout.PREFERRED_SIZE, 828, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdvancementCriteriaDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdvancementCriteriaDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdvancementCriteriaDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdvancementCriteriaDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdvancementCriteriaDisplay().setVisible(true);
                Thread one = new Thread() {
                public void run() {
                    try {
                        int numberisjad = 0;
                        JTextPane[] rayOfPanels = new JTextPane[42];
                        
                        rayOfPanels[0] = Inspire1stPlacePane;
                        rayOfPanels[1] = Inspire1stPlaceTeam;
                        
                        rayOfPanels[2] = WinningAllianceCaptainPane;
                        rayOfPanels[3] = WinningAllianceCaptainTeam;
                        
                        rayOfPanels[4] = Inspire2ndPlacePane;
                        rayOfPanels[5] = Inspire2ndPlaceTeam;
                        
                        rayOfPanels[6] = WinningAlliance1stPickPane;
                        rayOfPanels[7] = WinningAlliance1stPickTeam;
                        
                        rayOfPanels[8] = Inspire3rdPlacePane;
                        rayOfPanels[9] = Inspire3rdPlaceTeam;
                        
                        rayOfPanels[10] = WinningAlliance2ndPickPane;
                        rayOfPanels[11] = WinningAlliance2ndPickTeam;
                        
                        rayOfPanels[12] = Think1stPlacePane;
                        rayOfPanels[13] = Think1stPlaceTeam;
                        
                        rayOfPanels[14] = FinalistAllianceCaptainPane;
                        rayOfPanels[15] = FinalistAllianceCaptainTeam;
                        
                        rayOfPanels[16] = Connect1stPlacePane;
                        rayOfPanels[17] = Connect1stPlaceTeam;
                        
                        rayOfPanels[18] = FinalistAlliance1stPickPane;
                        rayOfPanels[19] = FinalistAlliance1stPickTeam;
                        
                        rayOfPanels[20] = Innovate1stPlacePane;
                        rayOfPanels[21] = Innovate1stPlaceTeam;
                        
                        rayOfPanels[22] = FinalistAlliance2ndPickPane;
                        rayOfPanels[23] = FinalistAlliance2ndPickTeam;
                        
                        rayOfPanels[24] = PTCDesign1stPlacePane;
                        rayOfPanels[25] = PTCDesign1stPlaceTeam;
                        
                        rayOfPanels[26] = Motivate1stPlacePane;
                        rayOfPanels[27] = Motivate1stPlaceTeam;
                        
                        rayOfPanels[28] = Control1stPlacePane;
                        rayOfPanels[29] = Control1stPlaceTeam;
                        
                        rayOfPanels[30] = HighestRankedWinningDivPane1;
                        rayOfPanels[31] = HighestRankedWinningDivTeam1;
                        
                        rayOfPanels[32] = Think2ndPlacePane;
                        rayOfPanels[33] = Think2ndPlaceTeam;
                        
                        rayOfPanels[34] = HighestRankedFinalistDivPane1;
                        rayOfPanels[35] = HighestRankedFinalistDivTeam1;
                        
                        rayOfPanels[36] = Connect2ndPlacePane;
                        rayOfPanels[37] = Connect2ndPlaceTeam;
                        
                        rayOfPanels[38] = HighestRankedWinningDivPane2;
                        rayOfPanels[39] = HighestRankedWinningDivTeam2;
                        
                        rayOfPanels[40] = Innovate2ndPlacePane;
                        rayOfPanels[41] = Innovate2ndPlaceTeam;
                        
                        while(true)
                        {
                            int numSpotsLeftPrimary = Integer.parseInt(NumberOfTeamsAdvancingPrimaryText.getText());
                            int numSpotsLeftSecondary = Integer.parseInt(NumberOfTeamsAdvancingSecondaryText.getText());
                            int curIndex = 0;
                            ArrayList<String> doneTeams = new ArrayList<String>();
                            while(numSpotsLeftPrimary>0 && curIndex < rayOfPanels.length/2)
                            {
                                String teamNum = rayOfPanels[curIndex*2+1].getText();
                                makePaneGreen(rayOfPanels[curIndex*2]);
                                makePaneGreen(rayOfPanels[curIndex*2+1]);
                                if(!doesRayListContain(doneTeams,teamNum))
                                {
                                    doneTeams.add(teamNum);
                                    numSpotsLeftPrimary--;
                                }
                                else
                                {
                                    makePaneGray(rayOfPanels[curIndex*2]);
                                    makePaneGray(rayOfPanels[curIndex*2+1]);
                                }
                                curIndex++;
                            }
                            while(curIndex < rayOfPanels.length/2)
                            {
                                makePaneRed(rayOfPanels[curIndex*2]);
                                makePaneRed(rayOfPanels[curIndex*2+1]);
                                curIndex++;
                            }
                            //makePaneGreen(Inspire1stPlacePane);
                            Thread.sleep(100);
                        }
                    } catch(InterruptedException v) {
                        System.out.println(v);
                    }
                }  
            };

            one.start();
            }
        });
        
    }
    
    public static boolean doesRayListContain(ArrayList<String> stuff, String s)
    {
        for(String word : stuff)
            if(word.equals(s))
                return true;
        return false;
    }
    
    public static void makePaneGray(JTextPane pane)
    {
        if(!pane.isFocusOwner()){
        StyledDocument doc = (StyledDocument)pane.getDocument();
        String words = pane.getText();
        pane.setText("");

        // Create a style object and then set the style attributes
        Style style = doc.addStyle("StyleName", null);

        StyleConstants.setBackground(style, new Color(224,224,224));

       
        // Append to document
        try{
        doc.insertString(doc.getLength(), words, style);}catch(Exception e){}
        }
    }
    
    public static void makePaneGreen(JTextPane pane)
    {
        if(!pane.isFocusOwner()){
        StyledDocument doc = (StyledDocument)pane.getDocument();
        String words = pane.getText();
        pane.setText("");

        // Create a style object and then set the style attributes
        Style style = doc.addStyle("StyleName", null);

        StyleConstants.setBackground(style, new Color(102,255,102));

       
        // Append to document
        try{
        doc.insertString(doc.getLength(), words, style);}catch(Exception e){}
        }
    }
    
    public static void makePaneRed(JTextPane pane)
    {
        if(!pane.isFocusOwner()){
        StyledDocument doc = (StyledDocument)pane.getDocument();
        String words = pane.getText();
        pane.setText("");

        // Create a style object and then set the style attributes
        Style style = doc.addStyle("StyleName", null);

        StyleConstants.setBackground(style, new Color(255,102,102));

        // Append to document
        try{
        doc.insertString(doc.getLength(), words, style);}catch(Exception e){}
        }
    }

    // Variables declaration - do not modify                     
    private static javax.swing.JTextPane Connect1stPlacePane;
    private static javax.swing.JTextPane Connect1stPlaceTeam;
    private static javax.swing.JTextPane Connect2ndPlacePane;
    private static javax.swing.JTextPane Connect2ndPlaceTeam;
    private static javax.swing.JTextPane Control1stPlacePane;
    private static javax.swing.JTextPane Control1stPlaceTeam;
    private static javax.swing.JTextPane FinalistAlliance1stPickPane;
    private static javax.swing.JTextPane FinalistAlliance1stPickTeam;
    private static javax.swing.JTextPane FinalistAlliance2ndPickPane;
    private static javax.swing.JTextPane FinalistAlliance2ndPickTeam;
    private static javax.swing.JTextPane FinalistAllianceCaptainPane;
    private static javax.swing.JTextPane FinalistAllianceCaptainTeam;
    private static javax.swing.JTextPane HighestRankedFinalistDivPane1;
    private static javax.swing.JTextPane HighestRankedFinalistDivTeam1;
    private static javax.swing.JTextPane HighestRankedWinningDivPane1;
    private static javax.swing.JTextPane HighestRankedWinningDivPane2;
    private static javax.swing.JTextPane HighestRankedWinningDivTeam1;
    private static javax.swing.JTextPane HighestRankedWinningDivTeam2;
    private static javax.swing.JTextPane Innovate1stPlacePane;
    private static javax.swing.JTextPane Innovate1stPlaceTeam;
    private static javax.swing.JTextPane Innovate2ndPlacePane;
    private static javax.swing.JTextPane Innovate2ndPlaceTeam;
    private static javax.swing.JTextPane Inspire1stPlacePane;
    private javax.swing.JTextPane Inspire1stPlacePane17;
    private javax.swing.JTextPane Inspire1stPlacePane22;
    private javax.swing.JTextPane Inspire1stPlacePane23;
    private javax.swing.JTextPane Inspire1stPlacePane24;
    private javax.swing.JTextPane Inspire1stPlacePane25;
    private javax.swing.JTextPane Inspire1stPlacePane26;
    private javax.swing.JTextPane Inspire1stPlacePane27;
    private javax.swing.JTextPane Inspire1stPlacePane28;
    private javax.swing.JTextPane Inspire1stPlacePane29;
    private javax.swing.JTextPane Inspire1stPlacePane30;
    private javax.swing.JTextPane Inspire1stPlacePane31;
    private javax.swing.JTextPane Inspire1stPlacePane32;
    private javax.swing.JTextPane Inspire1stPlacePane33;
    private javax.swing.JTextPane Inspire1stPlacePane34;
    private javax.swing.JTextPane Inspire1stPlacePane35;
    private javax.swing.JTextPane Inspire1stPlacePane36;
    private javax.swing.JTextPane Inspire1stPlacePane37;
    private javax.swing.JTextPane Inspire1stPlacePane38;
    private javax.swing.JTextPane Inspire1stPlacePane39;
    private javax.swing.JTextPane Inspire1stPlacePane40;
    private static javax.swing.JTextPane Inspire1stPlaceTeam;
    private static javax.swing.JTextPane Inspire2ndPlacePane;
    private static javax.swing.JTextPane Inspire2ndPlaceTeam;
    private static javax.swing.JTextPane Inspire3rdPlacePane;
    private static javax.swing.JTextPane Inspire3rdPlaceTeam;
    private static javax.swing.JTextPane Motivate1stPlacePane;
    private static javax.swing.JTextPane Motivate1stPlaceTeam;
    private javax.swing.JTextPane NumberOfTeamsAdvancingPrimaryPane;
    private static javax.swing.JTextPane NumberOfTeamsAdvancingPrimaryText;
    private static javax.swing.JTextPane NumberOfTeamsAdvancingSecondaryText;
    private javax.swing.JTextPane NumberOfTeamsAdvnacingSecondaryPane;
    private static javax.swing.JTextPane PTCDesign1stPlacePane;
    private static javax.swing.JTextPane PTCDesign1stPlaceTeam;
    private static javax.swing.JTextPane Think1stPlacePane;
    private static javax.swing.JTextPane Think1stPlaceTeam;
    private static javax.swing.JTextPane Think2ndPlacePane;
    private static javax.swing.JTextPane Think2ndPlaceTeam;
    private static javax.swing.JTextPane WinningAlliance1stPickPane;
    private static javax.swing.JTextPane WinningAlliance1stPickTeam;
    private static javax.swing.JTextPane WinningAlliance2ndPickPane;
    private static javax.swing.JTextPane WinningAlliance2ndPickTeam;
    private static javax.swing.JTextPane WinningAllianceCaptainPane;
    private static javax.swing.JTextPane WinningAllianceCaptainTeam;
    private javax.swing.JTextPane WinningAllianceCaptainTeam22;
    private javax.swing.JTextPane WinningAllianceCaptainTeam23;
    private javax.swing.JTextPane WinningAllianceCaptainTeam24;
    private javax.swing.JTextPane WinningAllianceCaptainTeam25;
    private javax.swing.JTextPane WinningAllianceCaptainTeam27;
    private javax.swing.JTextPane WinningAllianceCaptainTeam28;
    private javax.swing.JTextPane WinningAllianceCaptainTeam29;
    private javax.swing.JTextPane WinningAllianceCaptainTeam30;
    private javax.swing.JTextPane WinningAllianceCaptainTeam31;
    private javax.swing.JTextPane WinningAllianceCaptainTeam32;
    private javax.swing.JTextPane WinningAllianceCaptainTeam33;
    private javax.swing.JTextPane WinningAllianceCaptainTeam34;
    private javax.swing.JTextPane WinningAllianceCaptainTeam35;
    private javax.swing.JTextPane WinningAllianceCaptainTeam36;
    private javax.swing.JTextPane WinningAllianceCaptainTeam37;
    private javax.swing.JTextPane WinningAllianceCaptainTeam38;
    private javax.swing.JTextPane WinningAllianceCaptainTeam39;
    private javax.swing.JTextPane WinningAllianceCaptainTeam40;
    private javax.swing.JTextPane WinningAllianceCaptainTeam41;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private static javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane100;
    private javax.swing.JScrollPane jScrollPane101;
    private javax.swing.JScrollPane jScrollPane102;
    private javax.swing.JScrollPane jScrollPane103;
    private javax.swing.JScrollPane jScrollPane104;
    private javax.swing.JScrollPane jScrollPane105;
    private javax.swing.JScrollPane jScrollPane106;
    private javax.swing.JScrollPane jScrollPane107;
    private javax.swing.JScrollPane jScrollPane108;
    private javax.swing.JScrollPane jScrollPane109;
    private javax.swing.JScrollPane jScrollPane110;
    private javax.swing.JScrollPane jScrollPane111;
    private javax.swing.JScrollPane jScrollPane112;
    private javax.swing.JScrollPane jScrollPane113;
    private javax.swing.JScrollPane jScrollPane114;
    private javax.swing.JScrollPane jScrollPane115;
    private javax.swing.JScrollPane jScrollPane116;
    private javax.swing.JScrollPane jScrollPane117;
    private javax.swing.JScrollPane jScrollPane118;
    private javax.swing.JScrollPane jScrollPane119;
    private javax.swing.JScrollPane jScrollPane120;
    private javax.swing.JScrollPane jScrollPane121;
    private javax.swing.JScrollPane jScrollPane122;
    private javax.swing.JScrollPane jScrollPane123;
    private javax.swing.JScrollPane jScrollPane124;
    private javax.swing.JScrollPane jScrollPane125;
    private javax.swing.JScrollPane jScrollPane126;
    private javax.swing.JScrollPane jScrollPane127;
    private javax.swing.JScrollPane jScrollPane128;
    private javax.swing.JScrollPane jScrollPane129;
    private javax.swing.JScrollPane jScrollPane38;
    private static javax.swing.JScrollPane jScrollPane41;
    private javax.swing.JScrollPane jScrollPane42;
    private javax.swing.JScrollPane jScrollPane43;
    private javax.swing.JScrollPane jScrollPane44;
    private static javax.swing.JScrollPane jScrollPane45;
    private javax.swing.JScrollPane jScrollPane46;
    private javax.swing.JScrollPane jScrollPane47;
    private javax.swing.JScrollPane jScrollPane48;
    private javax.swing.JScrollPane jScrollPane49;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane50;
    private javax.swing.JScrollPane jScrollPane51;
    private javax.swing.JScrollPane jScrollPane52;
    private javax.swing.JScrollPane jScrollPane53;
    private javax.swing.JScrollPane jScrollPane54;
    private javax.swing.JScrollPane jScrollPane55;
    private javax.swing.JScrollPane jScrollPane56;
    private javax.swing.JScrollPane jScrollPane57;
    private javax.swing.JScrollPane jScrollPane58;
    private javax.swing.JScrollPane jScrollPane59;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane60;
    private javax.swing.JScrollPane jScrollPane61;
    private javax.swing.JScrollPane jScrollPane62;
    private javax.swing.JScrollPane jScrollPane63;
    private javax.swing.JScrollPane jScrollPane64;
    private javax.swing.JScrollPane jScrollPane65;
    private javax.swing.JScrollPane jScrollPane66;
    private javax.swing.JScrollPane jScrollPane67;
    private javax.swing.JScrollPane jScrollPane68;
    private javax.swing.JScrollPane jScrollPane69;
    private javax.swing.JScrollPane jScrollPane70;
    private javax.swing.JScrollPane jScrollPane71;
    private javax.swing.JScrollPane jScrollPane72;
    private javax.swing.JScrollPane jScrollPane73;
    private javax.swing.JScrollPane jScrollPane74;
    private javax.swing.JScrollPane jScrollPane75;
    private javax.swing.JScrollPane jScrollPane76;
    private javax.swing.JScrollPane jScrollPane77;
    private javax.swing.JScrollPane jScrollPane78;
    private javax.swing.JScrollPane jScrollPane79;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane80;
    private javax.swing.JScrollPane jScrollPane81;
    private javax.swing.JScrollPane jScrollPane82;
    private javax.swing.JScrollPane jScrollPane83;
    private javax.swing.JScrollPane jScrollPane84;
    private javax.swing.JScrollPane jScrollPane85;
    private javax.swing.JScrollPane jScrollPane86;
    private javax.swing.JScrollPane jScrollPane87;
    private javax.swing.JScrollPane jScrollPane88;
    private javax.swing.JScrollPane jScrollPane89;
    private javax.swing.JScrollPane jScrollPane90;
    private javax.swing.JScrollPane jScrollPane91;
    private javax.swing.JScrollPane jScrollPane92;
    private javax.swing.JScrollPane jScrollPane93;
    private javax.swing.JScrollPane jScrollPane94;
    private javax.swing.JScrollPane jScrollPane95;
    private javax.swing.JScrollPane jScrollPane96;
    private javax.swing.JScrollPane jScrollPane97;
    private javax.swing.JScrollPane jScrollPane98;
    private javax.swing.JScrollPane jScrollPane99;
    private javax.swing.JTextPane jTextPane38;
    private javax.swing.JTextPane jTextPane47;
    private javax.swing.JTextPane jTextPane48;
    private javax.swing.JTextPane jTextPane59;
    private javax.swing.JTextPane jTextPane60;
    private javax.swing.JTextPane jTextPane8;
    // End of variables declaration                   
}
